"""Source copiée dans chaque projet Studio pour résoudre son LLM d'exécution.

`RUNTIME_TEMPLATE_VERSION` est le seul mécanisme qui fait descendre un
correctif dans les projets déjà créés : l'adaptateur déployé porte sa
version en tête, et `ensure_runtime_adapter` réécrit dès qu'elle diffère.
Tout changement de la source ci-dessous impose d'incrémenter la version.
"""

#: v1 — première version (clé Gemini en query string, pas de métrage).
#: v2 — clé en en-tête `x-goog-api-key`, mode JSON, métrage et plafond,
#:      erreurs Gemini non nominales nommées.
RUNTIME_TEMPLATE_VERSION = "2"

RUNTIME_TEMPLATE_MARKER = "# agentl-studio-runtime-template: v"

RUNTIME_LLM_SOURCE = f'''{RUNTIME_TEMPLATE_MARKER}{RUNTIME_TEMPLATE_VERSION}
''' + r'''"""Runtime LLM resolver generated by AGENT-L Studio.

The authoring agent (Codex/Claude Code) is deliberately absent from this file:
it writes the project, while this adapter is called by the AGENT-L program.
Secrets are read from environment variables whose names are stored in
project.agentl.json; secret values are never written to the project.

Ce fichier est régénéré par le Studio quand sa version change. Toute
modification locale sera archivée dans `.history/` puis remplacée.
"""
from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from agentl import AnthropicLLM, MockLLM
from agentl.llm import LLM, _coerce, _parse_json, call_with_retry, missing_from

USAGE_FILENAME = "runtime_usage.json"


def _config() -> dict[str, Any]:
    path = Path(__file__).with_name("project.agentl.json")
    return json.loads(path.read_text(encoding="utf-8")) if path.is_file() else {}


class RuntimeBudgetExceeded(RuntimeError):
    """Le plafond de coût runtime déclaré dans le projet est atteint."""


class Meter:
    """Compte ce que l'oracle consomme et applique le plafond déclaré.

    Le coût n'est calculé que si un tarif est déclaré dans le projet. Sans
    tarif, le compteur reste honnête : appels et tokens sont mesurés, le
    coût est rendu `null` plutôt qu'un zéro qui se lirait « gratuit ».
    """

    def __init__(self, config: dict[str, Any]) -> None:
        self.config = config
        self.calls = 0
        self.input_tokens = 0
        self.output_tokens = 0
        self.price_in = float(config.get("runtimePricePerMTokIn", 0) or 0)
        self.price_out = float(config.get("runtimePricePerMTokOut", 0) or 0)
        self.max_cost = float(config.get("runtimeMaxCostUsd", 0) or 0)
        self.path = Path(__file__).with_name(USAGE_FILENAME)

    @property
    def priced(self) -> bool:
        return self.price_in > 0 or self.price_out > 0

    @property
    def cost_usd(self) -> float:
        return (self.input_tokens * self.price_in
                + self.output_tokens * self.price_out) / 1_000_000

    def guard(self) -> None:
        if self.priced and self.max_cost > 0 and self.cost_usd >= self.max_cost:
            raise RuntimeBudgetExceeded(
                f"plafond runtime atteint : {self.cost_usd:.4f} USD sur "
                f"{self.max_cost:.4f} USD apres {self.calls} appel(s)"
            )

    def record(self, input_tokens: int, output_tokens: int) -> None:
        self.calls += 1
        self.input_tokens += max(int(input_tokens or 0), 0)
        self.output_tokens += max(int(output_tokens or 0), 0)
        self.flush()

    def snapshot(self) -> dict[str, Any]:
        return {
            "calls": self.calls,
            "inputTokens": self.input_tokens,
            "outputTokens": self.output_tokens,
            "provider": self.config.get("runtimeProvider"),
            "model": self.config.get("runtimeModel"),
            "costUsd": round(self.cost_usd, 6) if self.priced else None,
            "maxCostUsd": self.max_cost or None,
            "priced": self.priced,
        }

    def flush(self) -> None:
        try:
            self.path.write_text(
                json.dumps(self.snapshot(), ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
        except OSError:
            pass                      # le metrage ne doit jamais casser un run


def _text_from_response(payload: dict[str, Any]) -> str:
    if isinstance(payload.get("output_text"), str):
        return payload["output_text"]
    chunks: list[str] = []
    for item in payload.get("output", []):
        for content in item.get("content", []):
            if content.get("type") in {"output_text", "text"} and content.get("text"):
                chunks.append(content["text"])
    return "\n".join(chunks)


def _http_json(request: urllib.request.Request, provider: str) -> dict[str, Any]:
    """Appelle le fournisseur en rendant son corps d'erreur lisible."""
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        body = ""
        try:
            body = exc.read().decode("utf-8", "replace")[:800]
        except Exception:
            pass
        message = body
        try:
            parsed = json.loads(body)
            message = parsed.get("error", {}).get("message") or body
        except Exception:
            pass
        exc.msg = f"{provider} a repondu {exc.code} : {message}"
        raise


class _JSONOracle(LLM):
    def __init__(self, model: str, config: dict[str, Any], meter: "Meter") -> None:
        self.model = model
        self.config = config
        self.meter = meter
        self.last_reason_missing = None

    def _call(self, system: str, prompt: str) -> str:
        raise NotImplementedError

    def _metered(self, system: str, prompt: str) -> str:
        self.meter.guard()
        return self._call(system, prompt)

    def reason(self, task, context, produce):
        system = ("Tu es l'oracle de raisonnement d'un runtime AGENT-L. Tu ne peux "
                  "executer aucune action. Reponds uniquement par un objet JSON "
                  "respectant exactement le schema demande.")
        prompt = (f"Tache : {task}\n\nSchema : {json.dumps(produce)}\n\n"
                  f"Contexte : {json.dumps(context, default=str)}")
        self.last_reason_missing = list(produce)
        parsed = _parse_json(call_with_retry(lambda: self._metered(system, prompt)))
        self.last_reason_missing = missing_from(parsed, produce)
        return _coerce(parsed, produce)

    def select_plan(self, context, candidates):
        if not candidates:
            return None
        raw = call_with_retry(lambda: self._metered(
            'Reponds uniquement par {"plan":"<nom>"}.',
            f"Plans : {candidates}\nContexte : {json.dumps(context, default=str)}",
        ))
        choice = _parse_json(raw).get("plan")
        return choice if choice in candidates else None


class GeminiRuntimeLLM(_JSONOracle):
    def _call(self, system: str, prompt: str) -> str:
        key_name = str(self.config.get("runtimeApiKeyEnv") or "GEMINI_API_KEY")
        key = os.environ.get(key_name, "")
        if not key:
            raise RuntimeError(f"variable {key_name} absente pour Gemini")
        url = ("https://generativelanguage.googleapis.com/v1beta/models/"
               f"{self.model}:generateContent")
        body = json.dumps({
            "systemInstruction": {"parts": [{"text": system}]},
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": 0,
                "maxOutputTokens": int(self.config.get("runtimeMaxOutputTokens", 4096)),
                "responseMimeType": "application/json",
            },
        }).encode("utf-8")
        request = urllib.request.Request(
            url, data=body,
            headers={"content-type": "application/json", "x-goog-api-key": key},
        )
        payload = _http_json(request, "Gemini")

        usage = payload.get("usageMetadata", {}) or {}
        self.meter.record(usage.get("promptTokenCount", 0),
                          usage.get("candidatesTokenCount", 0))

        blocked = (payload.get("promptFeedback") or {}).get("blockReason")
        if blocked:
            raise RuntimeError(
                f"Gemini a refuse la requete (blockReason={blocked}) : le contexte "
                f"envoye a l'oracle a declenche un filtre de securite."
            )
        candidates = payload.get("candidates") or []
        if not candidates:
            raise RuntimeError(
                "Gemini n'a rendu aucun candidat : requete filtree ou vide."
            )
        candidate = candidates[0]
        reason = candidate.get("finishReason")
        parts = (candidate.get("content") or {}).get("parts") or []
        text = "".join(part.get("text", "") for part in parts)
        if reason == "MAX_TOKENS" and not text.strip():
            raise RuntimeError(
                "Gemini a atteint maxOutputTokens avant d'ecrire du JSON : "
                "augmenter runtimeMaxOutputTokens dans le projet."
            )
        if reason in {"SAFETY", "RECITATION", "BLOCKLIST", "PROHIBITED_CONTENT"}:
            raise RuntimeError(f"Gemini a interrompu la reponse (finishReason={reason}).")
        if not text.strip():
            raise RuntimeError(
                f"Gemini a rendu une reponse vide (finishReason={reason or 'inconnu'})."
            )
        return text


class OpenAIRuntimeLLM(_JSONOracle):
    def _call(self, system: str, prompt: str) -> str:
        key_name = str(self.config.get("runtimeApiKeyEnv") or "OPENAI_API_KEY")
        key = os.environ.get(key_name, "")
        compatible = self.config.get("runtimeProvider") == "openai-compatible"
        if not key and not compatible:
            raise RuntimeError(f"variable {key_name} absente pour OpenAI")
        base = str(self.config.get("runtimeBaseUrl") or "https://api.openai.com/v1").rstrip("/")
        body = json.dumps({
            "model": self.model,
            "instructions": system,
            "input": prompt,
            "max_output_tokens": int(self.config.get("runtimeMaxOutputTokens", 4096)),
            "store": False,
        }).encode("utf-8")
        headers = {"content-type": "application/json"}
        if key:
            headers["authorization"] = f"Bearer {key}"
        request = urllib.request.Request(f"{base}/responses", data=body, headers=headers)
        payload = _http_json(request, "OpenAI")
        usage = payload.get("usage", {}) or {}
        self.meter.record(usage.get("input_tokens", 0), usage.get("output_tokens", 0))
        text = _text_from_response(payload)
        if not text.strip():
            status = payload.get("status") or payload.get("incomplete_details") or "inconnu"
            raise RuntimeError(f"reponse vide du fournisseur (statut : {status}).")
        return text


class MeteredAnthropicLLM(AnthropicLLM):
    """AnthropicLLM plus le compteur : le plafond doit valoir pour tous."""

    def __init__(self, meter: "Meter", **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self.meter = meter

    def _call(self, system: str, prompt: str) -> str:
        self.meter.guard()
        text = super()._call(system, prompt)
        # Anthropic ne rend pas l'usage par cette voie : compter l'appel et
        # estimer sur les caracteres plutot que de pretendre a l'exactitude.
        self.meter.record(len(system) + len(prompt) // 4, len(text) // 4)
        return text


def build_runtime_llm(fallback: LLM | None = None) -> LLM:
    config = _config()
    provider = str(config.get("runtimeProvider") or "mock")
    model = str(config.get("runtimeModel") or "")
    meter = Meter(config)
    if provider == "mock":
        return fallback or MockLLM()
    if provider == "google-gemini":
        if not model:
            raise RuntimeError("runtimeModel est requis pour Gemini")
        return GeminiRuntimeLLM(model, config, meter)
    if provider == "anthropic":
        key_name = str(config.get("runtimeApiKeyEnv") or "ANTHROPIC_API_KEY")
        if not model:
            raise RuntimeError("runtimeModel est requis pour Anthropic")
        key = os.environ.get(key_name, "")
        if not key:
            raise RuntimeError(f"variable {key_name} absente pour Anthropic")
        return MeteredAnthropicLLM(
            meter, model=model, api_key=key,
            max_tokens=int(config.get("runtimeMaxOutputTokens", 4096)),
        )
    if provider in {"openai", "openai-compatible"}:
        if not model:
            raise RuntimeError("runtimeModel est requis pour ce fournisseur")
        return OpenAIRuntimeLLM(model, config, meter)
    raise RuntimeError(f"fournisseur runtime inconnu : {provider}")
'''
